# Generated by Django 3.0.5 on 2020-07-29 18:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Profile/picture/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.CharField(max_length=200, null=True)),
                ('medications', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.IntegerField(blank=True, null=True)),
                ('prescription', models.IntegerField(blank=True, null=True)),
                ('message', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='Message/file/')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Message/pic/')),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_report', models.FileField(blank=True, null=True, upload_to='profile/health/document/')),
                ('diabetic', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('allergy', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('fiver', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('headache', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('caff', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('body_pain', models.CharField(blank=True, choices=[('No', 'No'), ('20%', '20%'), ('40%', '40%'), ('60%', '60%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='No', max_length=20, null=True)),
                ('b_des', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(choices=[('Eye/Year/Throat ', 'Eye/Year/Throat '), ('Dental', 'Dental'), ('Child ', 'child'), ('gynecologist ', 'gynecologist'), ('Dermatologists', 'Dermatologists'), ('Plastic Surgeons', 'Plastic Surgeons'), ('Psychiatrists', 'Psychiatrists'), ('General Surgeons', 'General Surgeons'), ('Urologists', 'Urologists'), ('Pathologists', 'Pathologists')], max_length=20, null=True)),
                ('degree', models.CharField(choices=[('MBBS', 'MBBS'), ('FCPS', 'FCPS')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name=django.contrib.auth.models.User)),
                ('date', models.DateField()),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('read', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PA', 'patient'), ('DOC', 'doctor'), ('EMP', 'employee'), ('OT', 'other')], default='PA', max_length=3)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
