# Generated by Django 3.0.5 on 2020-08-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account_appointment_docprofile_health_message_notification_password_prescription_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('PA', 'patient'), ('DOC', 'doctor'), ('EMP', 'employee'), ('OT', 'other')], default='PA', max_length=3),
        ),
    ]
