# Generated by Django 3.0.5 on 2020-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200810_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
