# Generated by Django 3.0.8 on 2020-11-11 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200810_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 18, 58, 8, 603956, tzinfo=utc)),
        ),
    ]
