# Generated by Django 3.0.8 on 2020-11-11 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201112_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 21, 2, 18, 366714, tzinfo=utc)),
        ),
    ]
